In [1]:
import numpy as np

In [2]:
def ej(jj,nn):
    ej     = np.zeros(nn-jj)
    ej[0]  = 1.0
    return ej

In [38]:
def qr(AA):
    
    nn = AA.shape[1]

    qq = np.eye(nn) + 1j*np.zeros([nn,nn])
    rr = np.array(AA)

    for jj in range(nn):

        # create hh reflection
        vv    = rr[jj:,jj];
        normx = np.abs(vv[0]);
        theta = np.arctan2(vv[0].imag, vv[0].real)
        vhat  = vv/np.linalg.norm(vv)
        uu    = vhat + ej(jj,nn)*np.exp(1j*theta)
        uhat  = uu/np.linalg.norm(uu)

        HH = -np.exp(-1j*theta)*(np.eye(nn-jj) - 2.0 * np.outer(uhat, uhat.conj()))

        rr[jj:, :] = HH @ rr[jj:, :];
        qq[:, jj:] = qq[:, jj:] @ HH; 
        
        return qq, rr

In [39]:
BB = 1.0*np.array([[1. , 2.],[3., 4.]]) + 1j*np.array([[5., 6.], [7., 8.]])

In [40]:
BB

array([[1.+5.j, 2.+6.j],
       [3.+7.j, 4.+8.j]])

In [41]:
qq, rr = qr(BB)

In [42]:
qq

array([[ 0.10910895-0.54554473j,  0.32732684-0.76376262j],
       [-0.008393  -0.83090658j, -0.10910895+0.54554473j]])

In [46]:
qq.conj().T @ rr

array([[1.+5.j, 2.+6.j],
       [3.+7.j, 4.+8.j]])

In [31]:
qq.conj().T @ qq      # AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

array([[ 1.00000000e+00+0.00000000e+00j, -2.15105711e-16-5.55111512e-17j],
       [-2.15105711e-16+5.55111512e-17j,  1.00000000e+00+0.00000000e+00j]])

In [47]:
rr

array([[ 9.16515139e+00+4.44089210e-16j,  1.09108945e+01-8.72871561e-01j],
       [-9.43689571e-16+0.00000000e+00j,  1.67859916e-01-4.02863797e-01j]])

In [13]:
# https://arxiv.org/pdf/math-ph/0609050.pdf