In [140]:
%reset -f
import numpy as np

In [141]:
AA = np.array([[1+2j, 3+4j],[5+6j, 7+8j]])

In [142]:
qq, rr = np.linalg.qr(AA)

In [143]:
print(qq)

[[-0.12309149-0.24618298j  0.73854895+0.61545745j]
 [-0.61545745-0.73854895j -0.24618298-0.12309149j]]


In [144]:
qq.conj().T @ qq

array([[ 1.00000000e+00+0.00000000e+00j, -2.63677968e-16-1.38777878e-16j],
       [-2.63677968e-16+1.38777878e-16j,  1.00000000e+00+0.00000000e+00j]])

In [145]:
qq @ rr

array([[1.+2.j, 3.+4.j],
       [5.+6.j, 7.+8.j]])

In [146]:
nn = AA.shape[1]

BB = np.real(AA)

qq = np.eye(nn) + 1j*np.zeros([nn,nn])
rr = BB

def ej(jj):
    ej     = np.zeros(nn-jj)
    ej[0]  = 1
    return ej

for jj in range(nn):
    
    # create hh reflection
    vv    = rr[jj:,jj];
    normx = np.linalg.norm(vv[0]);
    theta = np.arctan2(vv[0].imag, vv[0].real)
    vhat  = vv/np.linalg.norm(vv)
    uu    = vhat + ej(jj)*np.exp(1j*theta)
    uhat  = uu/np.linalg.norm(uu)
    
    HH = -np.exp(-1j*theta)*(np.eye(nn-jj) - 2 * np.outer(uhat, uhat.conj()))
    
    rr[jj:, :] = HH @ rr[jj:, :];
    qq[:, jj:] = qq[:, jj:] @ HH; 

<ipython-input-146-420aa3d1f68b>:25: ComplexWarning: Casting complex values to real discards the imaginary part
  rr[jj:, :] = HH @ rr[jj:, :];


In [147]:
rr

array([[5.09901951e+00, 7.45241314e+00],
       [6.66133815e-16, 1.56892908e+00]])

In [148]:
qq

array([[ 0.19611614+0.j,  0.98058068+0.j],
       [ 0.98058068+0.j, -0.19611614+0.j]])

In [149]:
qq @ rr

array([[1.+0.j, 3.+0.j],
       [5.+0.j, 7.+0.j]])

In [150]:
BB

array([[5.09901951e+00, 7.45241314e+00],
       [6.66133815e-16, 1.56892908e+00]])

In [151]:
AA

array([[5.09901951e+00+2.j, 7.45241314e+00+4.j],
       [6.66133815e-16+6.j, 1.56892908e+00+8.j]])

In [152]:
nn = AA.shape[1]
BB = np.real(AA)
print(BB)

[[5.09901951e+00 7.45241314e+00]
 [6.66133815e-16 1.56892908e+00]]


In [55]:
pp = np.array([1 , 2]);
ss = np.array([1j, 1j]);
np.outer(pp,ss.conj())

array([[0.-1.j, 0.-1.j],
       [0.-2.j, 0.-2.j]])